import Head from 'next/head';
import Link from 'next/link';
import { useEffect } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { postActions } from '../redux/posts/postsSlice';
import { PostInfoType } from '../utilities/types';

type Props = {
  postInfo: PostInfoType;
}


export default function Home({ postInfo }: Props) {
  const dispatch = useDispatch();
  const posts = useSelector(state => state.post.posts)
  useEffect(() => {
    dispatch(postActions.setPostList(postInfo.posts))
  }, [])

  console.log(posts)

  return (
    <>
      <Head>
        <title>Burak Blog List</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>Blog List</h1>

        <ul>
          {postInfo.posts.map(((post, index) => <li key={index}>
            <Link href={`/posts/${post.id}`}>{post.title}</Link>
          </li>))}
        </ul>
      </div >
    </>
  )
}


export async function getServerSideProps() {
  const responseDetail = await fetch('https://dummyjson.com/posts');
  const postInfo = await responseDetail.json();

  return {
    props: {
      postInfo,
    },
  };
}